#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
API_DIR="$ROOT_DIR"
UI_DIR="$ROOT_DIR/client"
MIGRATION_DIR="$ROOT_DIR/server/migrations"
read_env(){ awk -F= -v key="$1" '$0 !~ /^[[:space:]]*#/ && $1 == key {value=substr($0,index($0,"=")+1);gsub(/^[[:space:]]+|[[:space:]]+$/,"",value);gsub(/^["\047]|["\047]$/,"",value);print value;exit}' "$ENV_FILE"; }
load_key(){ local key="$1" parsed; [ -n "${!key-}" ] && return 0; [ -f "$ENV_FILE" ] || return 0; parsed="$(read_env "$key")"; [ -z "$parsed" ] || export "$key=$parsed"; }
for key in DATABASE_URL JWT_SECRET GOVERNANCE_TENANT_ID ENABLE_GENERATED_FEATURES ALLOW_SCHEMA_MIGRATION BACKEND_PORT FRONTEND_PORT PGSSLROOTCERT OPENROUTER_API_KEY OPENROUTER_MODEL OPENROUTER_BASE_URL PROVISION_ADMIN_EMAIL PROVISION_ADMIN_PASSWORD; do load_key "$key"; done
BACKEND_PORT="${BACKEND_PORT:-${PORT:-5001}}"; FRONTEND_PORT="${FRONTEND_PORT:-3000}"
export BACKEND_PORT FRONTEND_PORT
fail(){ printf 'error: %s\n' "$*" >&2; exit 1; }
check_config(){ local secret="${JWT_SECRET:-}"; command -v node >/dev/null||fail "node is required";command -v npm >/dev/null||fail "npm is required";[ -n "${DATABASE_URL:-}" ]||fail "DATABASE_URL is required";[ -n "${GOVERNANCE_TENANT_ID:-}" ]||fail "GOVERNANCE_TENANT_ID is required";[ "${#secret}" -ge 32 ]||fail "JWT_SECRET must contain at least 32 characters";case "$DATABASE_URL" in *example*|*changeme*|*password@*) fail "DATABASE_URL contains a placeholder";;esac;[ "${ENABLE_GENERATED_FEATURES:-false}" != "true" ]||[ "${NODE_ENV:-development}" != "production" ]||fail "generated features are forbidden in production";printf 'configuration valid for tenant %s\n' "$GOVERNANCE_TENANT_ID"; }
migrate(){ check_config;[ "${ALLOW_SCHEMA_MIGRATION:-0}" = "1" ]||fail "set ALLOW_SCHEMA_MIGRATION=1 for explicit migration";command -v psql >/dev/null||fail "psql is required";for migration in "$MIGRATION_DIR"/*.sql;do [ -f "$migration" ]||continue;psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$migration";done; }
port_free(){ lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1 && fail "port $1 is already in use; no process was changed" || true; }
start_services(){ local ui_run_dir="$UI_DIR";check_config;[ "$BACKEND_PORT" != "$FRONTEND_PORT" ]||fail "backend and frontend ports must differ";[ -n "${OPENROUTER_API_KEY:-}" ]||fail "OPENROUTER_API_KEY is required";[ -n "${OPENROUTER_MODEL:-}" ]||fail "OPENROUTER_MODEL is required";[ "${OPENROUTER_BASE_URL:-}" = "https://openrouter.ai/api/v1" ]||fail "canonical OPENROUTER_BASE_URL is required";[ "${ALLOW_SCHEMA_MIGRATION:-}" = true ]||fail "ALLOW_SCHEMA_MIGRATION=true is required";[ -d "$API_DIR/node_modules" ]||fail "API dependencies are missing; install explicitly";[ -d "$UI_DIR/node_modules" ]||fail "UI dependencies are missing; install explicitly";port_free "$BACKEND_PORT";port_free "$FRONTEND_PORT";node "$ROOT_DIR/server/scripts/prepare-runtime.js";if [ -n "${RUNTIME_PROJECT_SOURCE:-}" ]&&[ -d "$RUNTIME_PROJECT_SOURCE/client" ];then ui_run_dir="$RUNTIME_PROJECT_SOURCE/client";fi;(cd "$API_DIR" && PORT="$BACKEND_PORT" BACKEND_PORT="$BACKEND_PORT" node server/index.js) & api_pid=$!;(cd "$ui_run_dir" && PORT="$FRONTEND_PORT" FRONTEND_PORT="$FRONTEND_PORT" BACKEND_PORT="$BACKEND_PORT" HOST=127.0.0.1 BROWSER=none npm start) & ui_pid=$!;trap 'kill "$api_pid" "$ui_pid" 2>/dev/null || true;wait "$api_pid" "$ui_pid" 2>/dev/null || true' INT TERM EXIT;wait "$api_pid" "$ui_pid"; }
case "${1:-start}" in check) check_config;;migrate) migrate;;start) start_services;;*) fail "usage: $0 {check|migrate|start}";;esac
